version: '3.0'

services:
  master:
    image: graboskyc/mongodb-locust-scale:vectest
    ports:
     - "8089:8089"
    volumes:
      - locustdata:/mnt/locust
    command: --master -H http://master:8089
    env_file:
      - worker-variables.env
    deploy:
      resources:
        reservations:
          cpus: '48'
          memory: '8129M'
  
  worker:
    image: graboskyc/mongodb-locust-scale:vectest
    volumes:
      - locustdata:/mnt/locust
    command: --worker --master-host master
    env_file:
      - worker-variables.env
    deploy:
      mode: replicated
      replicas: 4

volumes:
  locustdata: