version: '3.0'

services:
  master:
    image: graboskyc/mongodb-locust-scale:v1.0.8
    ports:
     - "8089:8089"
    volumes:
      - locustdata:/mnt/locust
    command: --master -H http://master:8089
    env_file:
      - worker-variables.env
  
  worker:
    image: graboskyc/mongodb-locust-scale:v1.0.8
    volumes:
      - locustdata:/mnt/locust
    command: --worker --master-host master
    env_file:
      - worker-variables.env

volumes:
  locustdata: