version: '3.0'

services:
  master:
    image: graboskyc/mongodb-locust-scale:vectest
    ports:
     - "8089:8089"
    volumes:
      - locustdata:/mnt/locust
    command: --master -H http://master:8089
    env_file:
      - worker-variables.env
    deploy:
      resources:
        reservations:
          cpus: '40'
          memory: 64gb

  worker:
    image: graboskyc/mongodb-locust-scale:vectest
    volumes:
      - locustdata:/mnt/locust
    command: --worker --master-host master
    env_file:
      - worker-variables.env
    deploy:
      mode: replicated
      replicas: 8
      resources:
        reservations:
          cpus: '4'
          memory: 16gb

volumes:
  locustdata: